# Generated by Django 4.0.3 on 2022-03-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_conatact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatact',
            new_name='Contact',
        ),
    ]
