# Generated by Django 4.0.3 on 2022-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=500),
        ),
    ]
